<Project>
  <PropertyGroup>
    <!-- All Microsoft packages -->
    <MicrosoftPackageVersion>6.0.*</MicrosoftPackageVersion>
    <!-- Bing packages -->
    <BingUtilsPackageVersion>1.5.0</BingUtilsPackageVersion>
    <!-- Npoi packages -->
    <NpoiPackageVersion>[2.7.4]</NpoiPackageVersion>
    <!-- MiniExcel packages -->
    <MiniExcelPackageVersion>[1.46.0]</MiniExcelPackageVersion>
    <!-- ClosedXML packages -->
    <ClosedXmlPackageVersion>[0.105.1]</ClosedXmlPackageVersion>
  </PropertyGroup>
</Project>
