<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.tests.props" />

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Offices.AsposeCells\Bing.Offices.AsposeCells.csproj" />
  </ItemGroup>
</Project>
