<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BingOfficesPackageVersion Condition="'$(BingOfficesPackageVersion)' == ''">2.0.0</BingOfficesPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bing.Offices.Npoi" Version="$(BingOfficesPackageVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
</Project>
